apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1 # Replace with your desired region

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    minSize: 2
    maxSize: 3
    desiredCapacity: 2
    privateNetworking: true
    ssh:
      publicKeyName: my-ec2-key-pair

managedNodeGroups:
  - name: mng-1
    instanceType: m5.large
    minSize: 2
    maxSize: 3
    desiredCapacity: 2
