apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-prod-cluster
  region: us-west-2
availabilityZones: [us-west-2a, us-west-2b]
nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    availabilityZones: [us-west-2a]
    launchTemplate:
      name: my-launch-template
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 1
    availabilityZones: [us-west-2b]
    launchTemplate:
      name: my-launch-template
